# Generated by tools/unit_pipeline. Edit the YAML and rerun the pipeline for repeatable changes.
class_name GeneratedUnitData
extends Resource

@export var unit_id := ""
@export var display_name := ""
@export var faction := ""
@export var role := ""
@export var hp := 1
@export var armor := 0
@export var sight_range := 0.0
@export var speed := 0.0
@export var attack_type := ""
@export var weapon := ""
@export var damage := 0
@export var attack_range := 0.0
@export var cooldown := 1.0
@export var processed_model := ""
