extends SceneTree

const GENERATED_WARNING := "# Generated by tools/unit_pipeline. Edit the YAML and rerun the pipeline for repeatable changes.\n"

var _args := {}
var _force := false

func _init() -> void:
	_parse_args()
	var exit_code := _run()
	quit(exit_code)

func _parse_args() -> void:
	var argv := OS.get_cmdline_user_args()
	var i := 0
	while i < argv.size():
		var key := str(argv[i])
		if key == "--force":
			_force = true
			i += 1
			continue
		if key.begins_with("--") and i + 1 < argv.size():
			_args[key.trim_prefix("--")] = str(argv[i + 1])
			i += 2
			continue
		i += 1

func _run() -> int:
	if not _args.has("spec") or not _args.has("processed-glb") or not _args.has("report-json"):
		push_error("Expected --spec, --processed-glb and --report-json.")
		return 2
	var spec := _read_simple_yaml(_absolute_to_project_path(_args["spec"]))
	var unit_id := str(spec.get("unit_id", ""))
	if unit_id.is_empty():
		push_error("Spec missing unit_id.")
		return 2
	var processed_glb := _absolute_to_project_path(_args["processed-glb"])
	var report_json_path := _absolute_to_project_path(_args["report-json"])
	var unit_dir := "res://game/units/generated/%s" % unit_id
	var data_dir := "res://game/data/units"
	_ensure_dir(unit_dir)
	_ensure_dir(data_dir)
	var scene_path := "%s/%s.tscn" % [unit_dir, unit_id]
	var script_path := "%s/%s.gd" % [unit_dir, unit_id]
	var data_path := "%s/%s.tres" % [data_dir, unit_id]
	var data_script_path := "%s/generated_unit_data.gd" % data_dir
	var report_path := "%s/IMPORT_REPORT.md" % unit_dir
	if not _force:
		for path in [scene_path, script_path, data_path, report_path]:
			if FileAccess.file_exists(path):
				push_error("%s exists. Rerun with --force to overwrite generated files." % path)
				return 3
	var report := _load_json(report_json_path)
	if _force or not FileAccess.file_exists(data_script_path):
		_write_text(data_script_path, _unit_data_script_text())
	_write_text(script_path, _unit_script_text(spec))
	_write_text(data_path, _unit_data_text(spec))
	_write_text(scene_path, _scene_text(spec, processed_glb, script_path))
	if str(spec.get("combat.attack_type", "")) == "projectile":
		_create_projectile(spec)
	var generated := [scene_path, script_path, data_path, data_script_path, report_path]
	report["generated"] = generated
	report["godot_scene_path"] = scene_path.trim_prefix("res://")
	_write_text(report_json_path, JSON.stringify(report, "\t"))
	_write_text(report_path, _import_report_text(spec, report))
	return 0

func _absolute_to_project_path(path_value: String) -> String:
	var path := path_value.replace("\\", "/")
	var root := ProjectSettings.globalize_path("res://").replace("\\", "/").rstrip("/")
	if path.begins_with(root):
		return "res://" + path.substr(root.length()).trim_prefix("/")
	if path.begins_with("res://"):
		return path
	return path

func _ensure_dir(path: String) -> void:
	var dir := DirAccess.open("res://")
	var relative := path.trim_prefix("res://")
	dir.make_dir_recursive(relative)

func _write_text(path: String, content: String) -> void:
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		push_error("Could not write %s: %s" % [path, error_string(FileAccess.get_open_error())])
		return
	file.store_string(content)

func _read_text(path: String) -> String:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return ""
	return file.get_as_text()

func _load_json(path: String) -> Dictionary:
	var text := _read_text(path)
	if text.is_empty():
		return {}
	var parsed = JSON.parse_string(text)
	return parsed if typeof(parsed) == TYPE_DICTIONARY else {}

func _read_simple_yaml(path: String) -> Dictionary:
	var result := {}
	var stack: Array = [result]
	var indents: Array[int] = [0]
	for raw_line in _read_text(path).split("\n"):
		var line := raw_line.rstrip("\r")
		if line.strip_edges().is_empty() or line.strip_edges().begins_with("#"):
			continue
		var indent := line.length() - line.strip_edges(true, false).length()
		while indents.size() > 1 and indent <= indents[indents.size() - 1]:
			indents.pop_back()
			stack.pop_back()
		var trimmed := line.strip_edges()
		if trimmed.begins_with("- "):
			continue
		var colon := trimmed.find(":")
		if colon < 0:
			continue
		var key := trimmed.substr(0, colon).strip_edges()
		var value_text := trimmed.substr(colon + 1).strip_edges()
		var parent: Dictionary = stack[stack.size() - 1]
		var full_key := key
		if stack.size() > 1:
			var prefix := str(parent.get("__prefix", ""))
			full_key = "%s.%s" % [prefix, key] if not prefix.is_empty() else key
		if value_text.is_empty():
			var child := {"__prefix": full_key}
			parent[key] = child
			result[full_key] = child
			stack.append(child)
			indents.append(indent)
		else:
			var value = _parse_yaml_scalar(value_text)
			parent[key] = value
			result[full_key] = value
	return result

func _parse_yaml_scalar(value_text: String):
	if value_text == "true":
		return true
	if value_text == "false":
		return false
	if value_text == "[]":
		return []
	if value_text.is_valid_int():
		return int(value_text)
	if value_text.is_valid_float():
		return float(value_text)
	return value_text.trim_prefix("\"").trim_suffix("\"")

func _display_class_name(display_name: String) -> String:
	var output := ""
	for part in display_name.split(" "):
		output += part.capitalize().replace("_", "")
	return output

func _unit_script_text(spec: Dictionary) -> String:
	return GENERATED_WARNING + """extends Node3D

@export var unit_id := "%s"
@export var hp := %s
@export var speed := %s
@export var armor := %s
@export var sight_range := %s
@export var attack_range := %s
@export var damage := %s
@export var cooldown := %s
@export var faction := "%s"
@export var movement_type := "%s"
@export var attack_type := "%s"
@export var idle_animation := "idle"
@export var move_animation := "move"
@export var attack_animation := "attack"
@export var death_animation := "death"

var current_hp := hp
var cooldown_remaining := 0.0

func _ready() -> void:
	current_hp = hp
	# TODO: Bridge this generated Node3D unit to the existing RTSUnit/CombatSystem runtime.

func _process(delta: float) -> void:
	cooldown_remaining = maxf(0.0, cooldown_remaining - delta)

func can_attack() -> bool:
	return cooldown_remaining <= 0.0

func mark_attack_started() -> void:
	cooldown_remaining = cooldown

func take_damage(amount: int, _source: Node = null) -> void:
	current_hp = maxi(0, current_hp - maxi(0, amount - armor))
	if current_hp <= 0:
		queue_free()
""" % [
		str(spec.get("unit_id", "")),
		str(spec.get("stats.hp", 1)),
		str(spec.get("movement.speed", 1.0)),
		str(spec.get("stats.armor", 0)),
		str(spec.get("stats.sight_range", 0)),
		str(spec.get("combat.range", 0)),
		str(spec.get("combat.damage", 0)),
		str(spec.get("combat.cooldown", 1.0)),
		str(spec.get("faction", "")),
		str(spec.get("movement.type", "")),
		str(spec.get("combat.attack_type", "")),
	]

func _unit_data_text(spec: Dictionary) -> String:
	return """[gd_resource type="Resource" script_class="GeneratedUnitData" load_steps=2 format=3]

[ext_resource type="Script" path="res://game/data/units/generated_unit_data.gd" id="1_data"]

[resource]
script = ExtResource("1_data")
unit_id = "%s"
display_name = "%s"
faction = "%s"
role = "%s"
hp = %s
armor = %s
sight_range = %s
speed = %s
attack_type = "%s"
weapon = "%s"
damage = %s
attack_range = %s
cooldown = %s
processed_model = "%s"
""" % [
		str(spec.get("unit_id", "")),
		str(spec.get("display_name", "")),
		str(spec.get("faction", "")),
		str(spec.get("role", "")),
		str(spec.get("stats.hp", 1)),
		str(spec.get("stats.armor", 0)),
		str(spec.get("stats.sight_range", 0)),
		str(spec.get("movement.speed", 1.0)),
		str(spec.get("combat.attack_type", "")),
		str(spec.get("combat.weapon", "")),
		str(spec.get("combat.damage", 0)),
		str(spec.get("combat.range", 0)),
		str(spec.get("combat.cooldown", 1.0)),
		"art/processed_models/%s/%s.glb" % [str(spec.get("unit_id", "")), str(spec.get("unit_id", ""))],
	]

func _unit_data_script_text() -> String:
	return GENERATED_WARNING + """class_name GeneratedUnitData
extends Resource

@export var unit_id := ""
@export var display_name := ""
@export var faction := ""
@export var role := ""
@export var hp := 1
@export var armor := 0
@export var sight_range := 0.0
@export var speed := 0.0
@export var attack_type := ""
@export var weapon := ""
@export var damage := 0
@export var attack_range := 0.0
@export var cooldown := 1.0
@export var processed_model := ""
"""

func _scene_text(spec: Dictionary, processed_glb: String, script_path: String) -> String:
	var unit_id := str(spec.get("unit_id", "unit"))
	var root_name := _display_class_name(str(spec.get("display_name", unit_id)))
	var mesh_path := processed_glb
	if mesh_path.begins_with("res://"):
		mesh_path = mesh_path
	return """[gd_scene load_steps=9 format=3]

[ext_resource type="Script" path="%s" id="1_script"]
[ext_resource type="PackedScene" path="%s" id="2_model"]

[sub_resource type="SphereMesh" id="SphereMesh_shadow"]
radius = 0.42
height = 0.04

[sub_resource type="Animation" id="Animation_idle"]
resource_name = "idle"
length = 1.2
loop_mode = 1
tracks/0/type = "position_3d"
tracks/0/imported = false
tracks/0/enabled = true
tracks/0/path = NodePath("ModelRoot:position")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/keys = PackedFloat32Array(0, 1, 0, 0, 0, 0.6, 1, 0, 0.04, 0, 1.2, 1, 0, 0, 0)

[sub_resource type="Animation" id="Animation_move"]
resource_name = "move"
length = 0.7
loop_mode = 1
tracks/0/type = "position_3d"
tracks/0/imported = false
tracks/0/enabled = true
tracks/0/path = NodePath("ModelRoot:position")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/keys = PackedFloat32Array(0, 1, 0, 0, 0, 0.18, 1, 0, 0.08, -0.04, 0.36, 1, 0, 0, 0.04, 0.54, 1, 0, 0.08, -0.04, 0.7, 1, 0, 0, 0)

[sub_resource type="Animation" id="Animation_attack"]
resource_name = "attack"
length = 0.55
tracks/0/type = "position_3d"
tracks/0/imported = false
tracks/0/enabled = true
tracks/0/path = NodePath("ModelRoot:position")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/keys = PackedFloat32Array(0, 1, 0, 0, 0, 0.18, 1, 0, 0, -0.18, 0.32, 1, 0, 0.02, -0.42, 0.55, 1, 0, 0, 0)

[sub_resource type="Animation" id="Animation_death"]
resource_name = "death"
length = 1.0
tracks/0/type = "scale_3d"
tracks/0/imported = false
tracks/0/enabled = true
tracks/0/path = NodePath("ModelRoot:scale")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/keys = PackedFloat32Array(0, 1, 1, 1, 1, 0.45, 1, 1.05, 0.35, 1.05, 1, 1, 1.15, 0.02, 1.15)

[sub_resource type="AnimationLibrary" id="AnimationLibrary_generated"]
_data = {
&"attack": SubResource("Animation_attack"),
&"death": SubResource("Animation_death"),
&"idle": SubResource("Animation_idle"),
&"move": SubResource("Animation_move")
}

[node name="%sRoot" type="Node3D"]
script = ExtResource("1_script")

[node name="ModelRoot" type="Node3D" parent="."]

[node name="Model" parent="ModelRoot" instance=ExtResource("2_model")]

[node name="AnimationPlayer" type="AnimationPlayer" parent="."]
libraries/ = SubResource("AnimationLibrary_generated")

[node name="SelectionCircle" type="Node3D" parent="."]
visible = false

[node name="HealthBarAnchor" type="Node3D" parent="."]
position = Vector3(0, 2.05, 0)

[node name="ShadowBlob" type="MeshInstance3D" parent="."]
mesh = SubResource("SphereMesh_shadow")

[node name="VFXRoot" type="Node3D" parent="."]

[node name="MeleeHitMarker" type="Marker3D" parent="."]
position = Vector3(0, 0.9, -1.15)
""" % [script_path, mesh_path, root_name]

func _create_projectile(spec: Dictionary) -> void:
	var projectile_id := "%s_projectile" % str(spec.get("unit_id", "unit"))
	var dir := "res://game/projectiles/generated/%s" % projectile_id
	_ensure_dir(dir)
	_write_text("%s/%s.gd" % [dir, projectile_id], GENERATED_WARNING + "extends Node3D\n\n@export var speed := 12.0\n@export var damage := %s\n" % str(spec.get("combat.damage", 1)))
	_write_text("%s/%s.tscn" % [dir, projectile_id], "[gd_scene load_steps=2 format=3]\n\n[ext_resource type=\"Script\" path=\"%s/%s.gd\" id=\"1_script\"]\n\n[node name=\"%s\" type=\"Node3D\"]\nscript = ExtResource(\"1_script\")\n" % [dir, projectile_id, projectile_id.capitalize()])

func _import_report_text(spec: Dictionary, report: Dictionary) -> String:
	var lines := []
	lines.append("# Import Report: %s" % str(spec.get("display_name", spec.get("unit_id", ""))))
	lines.append("")
	lines.append("- Meshy called: %s" % ("yes" if bool(report.get("meshy_called", false)) else "no"))
	lines.append("- Raw model path: %s" % str(report.get("raw_model_path", "")))
	lines.append("- Processed GLB path: %s" % str(report.get("processed_glb_path", "")))
	lines.append("- Godot scene path: %s" % str(report.get("godot_scene_path", "")))
	lines.append("")
	lines.append("## Generated Scripts/Resources")
	for item in report.get("generated", []):
		lines.append("- %s" % str(item).trim_prefix("res://"))
	lines.append("")
	lines.append("## Warnings")
	var warnings: Array = report.get("warnings", [])
	if warnings.is_empty():
		lines.append("- None")
	else:
		for item in warnings:
			lines.append("- %s" % str(item))
	lines.append("")
	lines.append("## Manual Cleanup TODOs")
	for item in report.get("manual_todos", []):
		lines.append("- %s" % str(item))
	lines.append("")
	lines.append("## Animation Status")
	var animation_status: Dictionary = report.get("animation_status", {})
	for key in animation_status.keys():
		lines.append("- %s: %s" % [str(key), str(animation_status[key])])
	lines.append("")
	lines.append("## Errors Encountered")
	var errors: Array = report.get("errors", [])
	if errors.is_empty():
		lines.append("- None")
	else:
		for item in errors:
			lines.append("- %s" % str(item))
	return "\n".join(lines) + "\n"
