class_name UnitCatalog
extends RefCounted

const DEFINITIONS := {
	&"life_wizard": {
		"display_name": "Bad Kon Willow",
		"unit_family": &"kon",
		"form": &"hero",
		"max_hp": 260,
		"armor": 2,
		"magic_armor": 4,
		"move_speed_cells": 1,
		"attack_damage": 16,
		"attack_range_cells": 4,
		"attack_cooldown_ticks": 17,
		"attack_speed_seconds": 0.85,
		"attack_type": &"ranged_single",
		"attack_splash_radius_cells": 0.0,
		"projectile_speed": 680.0,
		"dual_cast": true,
		"sight_radius_cells": 9,
		"population": 1,
		"builder_unit": true,
		"role": "Hero builder. Dual-casts ranged attacks with a split staff and supports ranged allies through Observer Aura.",
		"passives": ["Builder unit", "Dual-cast staff"],
		"actives": ["Bio Mend", "Seal Away", "Observer Aura"],
		"activated_abilities": [&"bio_mend", &"seal_away", &"observer_aura"],
		"passive_abilities": [&"builder_unit", &"dual_cast_staff"],
		"animation_profile": {
			"frame_size": Vector2i(160, 192),
			"directions": 8,
			"actions": [&"idle", &"move", &"attack_dual_cast", &"bio_mend", &"seal_away", &"observer_aura", &"death"],
		},
	},
	&"fire_wizard": {
		"display_name": "Fire Wizard",
		"max_hp": 165,
		"move_speed_cells": 1,
		"attack_damage": 24,
		"attack_range_cells": 5,
		"attack_cooldown_ticks": 18,
		"projectile_speed": 780.0,
		"sight_radius_cells": 9,
		"population": 1,
	},
	&"evangalion_wizard": {
		"display_name": "Evangalion",
		"max_hp": 190,
		"move_speed_cells": 1,
		"attack_damage": 20,
		"attack_range_cells": 5,
		"attack_cooldown_ticks": 18,
		"projectile_speed": 760.0,
		"sight_radius_cells": 10,
		"population": 1,
	},
	&"life_treant": {
		"display_name": "Treant",
		"max_hp": 95,
		"move_speed_cells": 1,
		"attack_damage": 9,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 20,
		"sight_radius_cells": 6,
		"population": 1,
	},
	&"terrible_thing": {
		"display_name": "Terrible Thing",
		"unit_family": &"terrible_thing",
		"form": &"base",
		"max_hp": 64,
		"armor": 0,
		"magic_armor": 0,
		"move_speed_cells": 1,
		"attack_damage": 8,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 16,
		"attack_speed_seconds": 0.8,
		"attack_type": &"melee",
		"attack_splash_radius_cells": 0.0,
		"sight_radius_cells": 6,
		"population": 1,
		"cost_bio": 28,
		"train_time_seconds": 3.8,
		"evolves_to": &"gripper",
		"evolution_xp_required": 90,
		"role": "Cheap swarm unit. Charges and grapples, but is weak alone and detonates when killed by allied friendly fire.",
		"passives": ["Sacrificial explosion", "Pack grappler"],
		"actives": ["Charge", "Grapple"],
		"activated_abilities": [&"charge", &"grapple"],
		"passive_abilities": [&"sacrificial_explosion", &"pack_grappler"],
		"grapple_power": 1,
		"grapple_seconds": 2.4,
		"grapple_cooldown_seconds": 4.0,
		"charge_speed_multiplier": 1.55,
		"death_explosion_damage": 18,
		"death_explosion_radius": 92.0,
		"friendly_fire_explodes": true,
		"animation_profile": {
			"frame_size": Vector2i(128, 128),
			"directions": 8,
			"actions": [&"idle", &"move", &"attack_melee", &"charge", &"grapple", &"evolve", &"death_explode"],
		},
	},
	&"gripper": {
		"display_name": "Gripper",
		"unit_family": &"terrible_thing",
		"form": &"evolved",
		"max_hp": 132,
		"armor": 4,
		"magic_armor": 2,
		"move_speed_cells": 1,
		"attack_damage": 14,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 16,
		"attack_speed_seconds": 0.8,
		"attack_type": &"melee",
		"attack_splash_radius_cells": 0.0,
		"sight_radius_cells": 6,
		"population": 1,
		"cost_bio": 0,
		"role": "Evolved Terrible Thing. Tougher, no longer detonates to allied fire, and its grapple roots nearby enemies.",
		"passives": ["Pack grappler", "Area root grapple"],
		"actives": ["Charge", "Grapple"],
		"activated_abilities": [&"charge", &"grapple"],
		"passive_abilities": [&"pack_grappler", &"area_root_grapple"],
		"grapple_power": 2,
		"grapple_seconds": 2.0,
		"grapple_cooldown_seconds": 3.6,
		"grapple_aoe_radius": 96.0,
		"charge_speed_multiplier": 1.45,
		"friendly_fire_explodes": false,
		"animation_profile": {
			"frame_size": Vector2i(128, 128),
			"directions": 8,
			"actions": [&"idle", &"move", &"attack_melee", &"charge", &"grapple_aoe", &"death"],
		},
	},
	&"awful_thing": {
		"display_name": "Awful Thing (Deprecated)",
		"max_hp": 132,
		"armor": 4,
		"magic_armor": 2,
		"move_speed_cells": 1,
		"attack_damage": 14,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 16,
		"attack_speed_seconds": 0.8,
		"attack_type": &"melee",
		"sight_radius_cells": 6,
		"population": 1,
		"cost_bio": 0,
		"role": "Compatibility alias for Gripper. New content should use gripper.",
		"passives": ["Pack grappler", "Area root grapple"],
		"actives": ["Charge", "Grapple"],
		"grapple_power": 2,
		"grapple_seconds": 2.0,
		"grapple_cooldown_seconds": 3.6,
		"grapple_aoe_radius": 96.0,
		"charge_speed_multiplier": 1.45,
		"friendly_fire_explodes": false,
	},
	&"horror": {
		"display_name": "Horror",
		"unit_family": &"horror",
		"form": &"base",
		"max_hp": 72,
		"armor": 1,
		"magic_armor": 1,
		"move_speed_cells": 1,
		"attack_damage": 10,
		"attack_range_cells": 4,
		"attack_cooldown_ticks": 20,
		"attack_speed_seconds": 1.0,
		"attack_type": &"ranged_single",
		"attack_splash_radius_cells": 0.0,
		"projectile_speed": 720.0,
		"sight_radius_cells": 8,
		"population": 1,
		"cost_bio": 65,
		"train_time_seconds": 7.0,
		"evolves_to": &"hunter",
		"evolution_xp_required": 80,
		"evolution_speed_bonus": 22,
		"role": "Fast ranged skirmisher. Evolution pushes it toward speed and kiting.",
		"passives": ["Evolution speed gain"],
		"actives": [],
		"activated_abilities": [],
		"passive_abilities": [&"evolution_speed_gain"],
		"animation_profile": {
			"frame_size": Vector2i(128, 128),
			"directions": 8,
			"actions": [&"idle", &"move", &"attack_ranged", &"evolve", &"death"],
		},
	},
	&"hunter": {
		"display_name": "Hunter",
		"unit_family": &"horror",
		"form": &"evolved",
		"max_hp": 108,
		"armor": 2,
		"magic_armor": 2,
		"move_speed_cells": 1,
		"attack_damage": 16,
		"attack_range_cells": 4,
		"attack_cooldown_ticks": 18,
		"attack_speed_seconds": 0.9,
		"attack_type": &"ranged_single",
		"attack_splash_radius_cells": 0.0,
		"projectile_speed": 780.0,
		"sight_radius_cells": 9,
		"population": 1,
		"cost_bio": 0,
		"role": "Evolved Horror. Builds Hunt charges for burst attacks with double range and double damage.",
		"passives": ["Hunt charge"],
		"actives": [],
		"activated_abilities": [],
		"passive_abilities": [&"hunt"],
		"hunt_charge_seconds": 10.0,
		"hunt_max_charges": 1,
		"hunt_range_multiplier": 2.0,
		"hunt_damage_multiplier": 2.0,
		"animation_profile": {
			"frame_size": Vector2i(128, 128),
			"directions": 8,
			"actions": [&"idle", &"move", &"attack_ranged", &"hunt_attack", &"death"],
		},
	},
	&"apex": {
		"display_name": "Apex",
		"unit_family": &"apex",
		"form": &"base",
		"max_hp": 150,
		"armor": 3,
		"magic_armor": 2,
		"move_speed_cells": 1,
		"attack_damage": 17,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 22,
		"attack_speed_seconds": 1.1,
		"attack_type": &"melee",
		"attack_splash_radius_cells": 0.0,
		"sight_radius_cells": 8,
		"population": 2,
		"cost_bio": 110,
		"train_time_seconds": 10.0,
		"heal_per_attack": 8,
		"evolves_to": &"champion",
		"evolution_xp_required": 120,
		"role": "Support predator. Heals in combat and can eat allied units for evolution.",
		"passives": ["Combat healing", "Carrion evolution"],
		"actives": ["Eat ally"],
		"activated_abilities": [&"consume_ally"],
		"passive_abilities": [],
		"animation_profile": {
			"frame_size": Vector2i(160, 160),
			"directions": 8,
			"actions": [&"idle", &"move", &"attack_melee", &"consume_ally", &"heal_pulse", &"evolve", &"death"],
		},
	},
	&"champion": {
		"display_name": "Champion",
		"unit_family": &"apex",
		"form": &"evolved",
		"max_hp": 260,
		"armor": 6,
		"magic_armor": 4,
		"move_speed_cells": 1,
		"attack_damage": 30,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 13,
		"attack_speed_seconds": 0.65,
		"attack_type": &"melee",
		"attack_splash_radius_cells": 0.0,
		"sight_radius_cells": 9,
		"population": 2,
		"cost_bio": 0,
		"role": "Evolved Apex. Gains attack speed and armor as health falls; Consume Ally heals instead of granting XP.",
		"passives": ["Combat healing", "Wounded champion"],
		"actives": ["Eat ally"],
		"activated_abilities": [&"consume_ally"],
		"passive_abilities": [&"wounded_champion"],
		"low_health_attack_speed_bonus": 0.35,
		"low_health_armor_bonus": 4,
		"consume_ally_heals": true,
		"animation_profile": {
			"frame_size": Vector2i(160, 160),
			"directions": 8,
			"actions": [&"idle", &"move", &"attack_melee", &"consume_ally", &"wounded_frenzy", &"death"],
		},
	},
	&"apex_predator": {
		"display_name": "Apex Predator (Deprecated)",
		"max_hp": 260,
		"armor": 6,
		"magic_armor": 4,
		"move_speed_cells": 1,
		"attack_damage": 30,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 13,
		"attack_speed_seconds": 0.65,
		"attack_type": &"melee",
		"sight_radius_cells": 9,
		"population": 2,
		"cost_bio": 0,
		"role": "Compatibility alias for Champion. New content should use champion.",
		"passives": ["Combat healing", "Wounded champion"],
		"actives": ["Eat ally"],
	},
	&"spawner": {
		"display_name": "Spawner",
		"unit_family": &"spawner",
		"form": &"base",
		"max_hp": 360,
		"armor": 5,
		"magic_armor": 3,
		"move_speed_cells": 1,
		"attack_damage": 38,
		"attack_range_cells": 8,
		"attack_cooldown_ticks": 48,
		"attack_speed_seconds": 2.4,
		"attack_type": &"ranged_aoe",
		"attack_splash_radius_cells": 1.8,
		"projectile_speed": 460.0,
		"sight_radius_cells": 9,
		"population": 4,
		"cost_bio": 210,
		"train_time_seconds": 18.0,
		"role": "Slow siege organism. Maintains drones, roots to fire a long-range AoE cannon.",
		"passives": ["Drone brood cap 2", "Rooted artillery"],
		"actives": ["Summon drone", "Root", "Uproot"],
		"activated_abilities": [&"summon_drone", &"root", &"uproot"],
		"passive_abilities": [&"spawn_drones"],
		"drone_archetype": &"spawner_drone",
		"drone_cap": 2,
		"drone_summon_cost_bio": 12,
		"drone_summon_cooldown_seconds": 8.0,
		"shot_cost_bio": 4,
		"aoe_radius": 116.0,
		"requires_root_to_fire": true,
		"root_cast_seconds": 2.0,
		"uproot_cast_seconds": 2.0,
		"evolution_xp_required": 180,
		"evolves_to": &"winged_spawner",
		"animation_profile": {
			"frame_size": Vector2i(192, 192),
			"directions": 8,
			"actions": [&"idle", &"move", &"root_cast", &"rooted_idle", &"artillery_attack", &"uproot_cast", &"summon_drone", &"evolve_wings", &"death"],
		},
	},
	&"winged_spawner": {
		"display_name": "Winged Spawner",
		"unit_family": &"spawner",
		"form": &"evolved",
		"max_hp": 430,
		"armor": 5,
		"magic_armor": 5,
		"move_speed_cells": 1,
		"attack_damage": 44,
		"attack_range_cells": 8,
		"attack_cooldown_ticks": 42,
		"attack_speed_seconds": 2.1,
		"attack_type": &"ranged_aoe",
		"attack_splash_radius_cells": 1.9,
		"projectile_speed": 500.0,
		"sight_radius_cells": 10,
		"population": 4,
		"cost_bio": 0,
		"role": "Evolved flying Spawner. Mobile artillery that no longer roots to fire.",
		"passives": ["Flying artillery", "Drone brood cap 2"],
		"actives": ["Summon drone"],
		"activated_abilities": [&"summon_drone"],
		"passive_abilities": [&"spawn_drones", &"flying", &"moving_attack_penalty"],
		"drone_archetype": &"spawner_drone",
		"drone_cap": 2,
		"drone_summon_cost_bio": 10,
		"drone_summon_cooldown_seconds": 7.0,
		"shot_cost_bio": 3,
		"aoe_radius": 124.0,
		"ignores_terrain": true,
		"evolution_speed_bonus": 45,
		"takeoff_seconds": 0.5,
		"landing_seconds": 0.5,
		"moving_attack_range_multiplier": 0.5,
		"moving_attack_damage_multiplier": 0.5,
		"animation_profile": {
			"frame_size": Vector2i(192, 192),
			"directions": 8,
			"actions": [&"idle_flying", &"move_flying", &"takeoff", &"landing", &"artillery_attack", &"summon_drone", &"death"],
		},
	},
	&"stone_face_serpent": {
		"display_name": "Stone Face Serpent",
		"unit_family": &"stone_face_serpent",
		"form": &"growth",
		"tier": 2,
		"max_hp": 240,
		"armor": 5,
		"magic_armor": 3,
		"move_speed_cells": 1,
		"attack_damage": 24,
		"attack_range_cells": 2,
		"attack_cooldown_ticks": 26,
		"attack_speed_seconds": 1.3,
		"attack_type": &"melee",
		"attack_splash_radius_cells": 0.0,
		"sight_radius_cells": 8,
		"population": 3,
		"cost_bio": 165,
		"train_time_seconds": 14.0,
		"role": "Hybrid stone serpent. Grows through evolution and can turn its length into an impassible stone wall.",
		"passives": ["Poison sting", "Coil strike", "Multi-growth evolution"],
		"actives": ["Stone Form"],
		"activated_abilities": [&"stone_form"],
		"passive_abilities": [&"poison_sting", &"coil_strike"],
		"unit_type_tags": [&"evolution"],
		"evolution_xp_required": 105,
		"max_evolution_level": 5,
		"stone_form_base_length": 1,
		"stone_form_cast_seconds": 2.0,
		"stone_form_cooldown_seconds": 10.0,
		"growth_hp_bonus": 58,
		"growth_damage_bonus": 5,
		"growth_range_cells_bonus": 0.35,
		"growth_size_bonus": 3.0,
		"poison_damage_per_second": 5.0,
		"poison_duration_seconds": 4.0,
		"animation_profile": {
			"frame_size": Vector2i(192, 192),
			"directions": 8,
			"actions": [&"idle", &"move", &"attack_melee", &"poison_sting", &"stone_cast", &"stone_idle", &"revert_stone", &"evolve_growth", &"death"],
		},
	},
	&"spawner_drone": {
		"display_name": "Spawner Drone",
		"max_hp": 34,
		"move_speed_cells": 1,
		"attack_damage": 5,
		"attack_range_cells": 3,
		"attack_cooldown_ticks": 17,
		"projectile_speed": 690.0,
		"sight_radius_cells": 7,
		"population": 0,
		"cost_bio": 0,
		"role": "Short-lived flying support drone from a Spawner.",
		"passives": ["Flying support", "Bound to Spawner brood"],
		"actives": [],
		"ignores_terrain": true,
		"lifetime_seconds": 45.0,
	},
	&"vampire_mushroom_thrall": {
		"display_name": "Vampire Mushroom Thrall",
		"max_hp": 55,
		"move_speed_cells": 1,
		"attack_damage": 7,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 24,
		"sight_radius_cells": 7,
		"population": 1,
	},
	&"bloodcap_runner": {
		"display_name": "Bloodcap Runner",
		"max_hp": 38,
		"move_speed_cells": 1,
		"attack_damage": 5,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 16,
		"sight_radius_cells": 8,
		"population": 1,
	},
	&"spore_spitter": {
		"display_name": "Spore Spitter",
		"max_hp": 44,
		"move_speed_cells": 1,
		"attack_damage": 8,
		"attack_range_cells": 4,
		"attack_cooldown_ticks": 28,
		"projectile_speed": 520.0,
		"sight_radius_cells": 8,
		"population": 1,
	},
	&"bloodcap_brute": {
		"display_name": "Bloodcap Brute",
		"max_hp": 145,
		"move_speed_cells": 1,
		"attack_damage": 17,
		"attack_range_cells": 1,
		"attack_cooldown_ticks": 34,
		"sight_radius_cells": 7,
		"population": 2,
	},
	&"mycelium_boss": {
		"display_name": "Mycelium Matriarch",
		"max_hp": 3000,
		"move_speed_cells": 1,
		"attack_damage": 95,
		"attack_range_cells": 3,
		"attack_cooldown_ticks": 14,
		"sight_radius_cells": 10,
		"population": 6,
		"ignores_terrain": true,
	},
	&"wizard_tower": {
		"display_name": "Wizard Tower",
		"max_hp": 700,
		"build_time_seconds": 0.0,
		"auto_evolves": true,
		"evolution_seconds": 90.0,
		"footprint": Vector2i(3, 3),
	},
	&"bio_absorber": {
		"display_name": "Bio Absorber",
		"max_hp": 260,
		"income_per_tick": 16,
		"cost_bio": 90,
		"build_time_seconds": 4.0,
		"auto_evolves": true,
		"evolution_seconds": 75.0,
		"upgrade_choices": [&"heal_aura", &"bio_launcher"],
		"footprint": Vector2i(2, 2),
	},
	&"barracks": {
		"display_name": "Barracks",
		"max_hp": 380,
		"cost_bio": 120,
		"build_time_seconds": 6.0,
		"auto_evolves": true,
		"evolution_seconds": 100.0,
		"footprint": Vector2i(3, 3),
		"production": [&"terrible_thing", &"horror", &"apex", &"spawner", &"stone_face_serpent"],
	},
	&"terrible_vault": {
		"display_name": "Terrible Vault",
		"max_hp": 320,
		"cost_bio": 140,
		"build_time_seconds": 7.0,
		"auto_evolves": true,
		"evolution_seconds": 120.0,
		"footprint": Vector2i(2, 2),
	},
	&"vinewall": {
		"display_name": "Vinewall",
		"max_hp": 220,
		"starts_at_hp_percent": 0.5,
		"cost_bio": 35,
		"build_time_seconds": 1.2,
		"regeneration_per_second": 5,
		"retaliation_damage": 8,
		"evolution_xp_required": 80,
		"footprint": Vector2i(1, 1),
	},
	&"bio_launcher": {
		"display_name": "Bio Launcher",
		"max_hp": 260,
		"cost_bio": 130,
		"build_time_seconds": 6.0,
		"attack_damage": 24,
		"attack_range_cells": 9,
		"attack_cooldown_ticks": 40,
		"shot_cost_bio": 3,
		"aoe_radius": 92.0,
		"can_uproot": true,
		"evolution_xp_required": 120,
		"footprint": Vector2i(2, 2),
	},
}

static func get_definition(archetype: StringName) -> Dictionary:
	return DEFINITIONS.get(archetype, {})

static func max_hp(archetype: StringName) -> int:
	return int(DEFINITIONS.get(archetype, {}).get("max_hp", 40))

static func attack_damage(archetype: StringName) -> int:
	return int(DEFINITIONS.get(archetype, {}).get("attack_damage", 0))

static func attack_range_cells(archetype: StringName) -> int:
	return int(DEFINITIONS.get(archetype, {}).get("attack_range_cells", 0))

static func cost_bio(archetype: StringName) -> int:
	return int(DEFINITIONS.get(archetype, {}).get("cost_bio", 0))

static func train_time(archetype: StringName) -> float:
	return float(DEFINITIONS.get(archetype, {}).get("train_time_seconds", 0.0))
